"""empty message

Revision ID: 4a93e7a4ba3f
Revises: 
Create Date: 2019-05-06 17:48:30.740288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a93e7a4ba3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filepaths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filepaths')
    # ### end Alembic commands ###
