"""empty message

Revision ID: 8c684b973618
Revises: 7e3d153c7d43
Create Date: 2019-05-18 19:54:35.762222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c684b973618'
down_revision = '7e3d153c7d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('extension', sa.String(length=16), nullable=False))
    op.add_column('problems', sa.Column('language_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'problems', 'languages', ['language_id'], ['language_id'])
    op.drop_column('problems', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('language', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_column('problems', 'language_id')
    op.drop_column('languages', 'extension')
    # ### end Alembic commands ###
