"""empty message

Revision ID: c16d45dac908
Revises: 4a93e7a4ba3f
Create Date: 2019-05-06 17:53:39.573960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c16d45dac908'
down_revision = '4a93e7a4ba3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filepaths', sa.Column('contents', sa.Text(), nullable=False))
    op.drop_column('filepaths', 'filepath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filepaths', sa.Column('filepath', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False))
    op.drop_column('filepaths', 'contents')
    # ### end Alembic commands ###
